runtime: nodejs18
service: personal-portfolio
handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
    secure: always
    # catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always